{capture assign="title"}{t}Account{/t}{/capture}
{include file='header.tpl' title=$title page_active='user'}
<div class="container">
	{if $settings_totp_enabled and $totp_enable and !$totp_success}
	<div class="col-md-7">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">{t}Enable two-factor authentication{/t}</h3>
			</div>
			<div class="panel-body">
				<form class="form-horizontal" method="post" action="?page=user&totp_enable=true">
				<p>{t}Please scan the image with Google Authenticator or add it manually by entering this secret key:{/t} <strong>{$totp_secret}</strong></p>
				<div class="alert alert-info">
					<i class="fa fa-info-circle" aria-hidden="true"></i> {t}It's strongly recommended that you save this secret key in case you need to recover your two-factor authentication.{/t}
				</div>
				{if $totp_error}
					<div class="alert alert-danger"><i class="fa fa-exclamation-circle" aria-hidden="true"></i> {t}Verification failed. Please try again.{/t}</div>
				{/if}
				<p>{t}Now enter a 6-digit token to verify and enable two-factor authentication.{/t}</p>
				<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-lock" aria-hidden="true"></i></span>
					<input type="text" class="form-control" name="totp_verify_key" id="totp_verify_key" placeholder="{t}Two-factor token{/t}" pattern="[0-9]{literal}{6}{/literal}" autocomplete="off">
					<div class="input-group-btn">
						<button type="submit" class="btn btn-success"><i class="fa fa-check-circle" aria-hidden="true"></i> {t}Enable{/t}</button>
					</div>
				</div>
				<input type="hidden" name="totp_secret" id="totp_secret" value="{$totp_secret}">
				</form>
			</div>
		</div>
	</div>
	<div class="col-md-5">
		<div class="panel panel-default">
			<div class="panel-body">
				<p class="text-center">
					{$totp_qr_svg}
				</p>
			</div>
		</div>
	</div>
	{else if $settings_totp_enabled and $totp_disable and !$totp_disable_success}
	<div class="col-md-offset-3 col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">{t}Disable two-factor authentication{/t}</h3>
			</div>
			<div class="panel-body">
				<form class="form-horizontal" method="post" action="?page=user&totp_disable=true">
				{if $totp_error}
					<div class="alert alert-danger"><i class="fa fa-exclamation-circle" aria-hidden="true"></i> {t}Verification failed. Please try again.{/t}</div>
				{/if}
				<p>{t}To disable two-factor authentication please enter a key 6-digit token.{/t}</p>
				<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-lock" aria-hidden="true"></i></span>
					<input type="text" class="form-control" name="totp_verify_key" id="totp_verify_key" placeholder="{t}Two-factor token{/t}" pattern="[0-9]{literal}{6}{/literal}" autocomplete="off">
					<div class="input-group-btn">
						<button type="submit" class="btn btn-danger"><i class="fa fa-chain-broken" aria-hidden="true"></i> {t}Disable{/t}</button>
					</div>
				</div>
				</form>
			</div>
		</div>
	</div>
	{else}
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">{t}Permissions{/t}</h3>
			</div>
			<div class="panel-body">
				{if not $access_mail and not $access_domain}
					<p>
						{t}You have no restrictions, you may view messages to/from any domain.{/t}
					</p>
				{else}
					<p>
					{t}You are authorized to view messages sent from/to the following{/t}
					{if $access_domain}
						{t}domains:{/t}</p>
						<ul>
							{foreach $access_domain as $access}
								<li>{$access|escape}</li>
							{/foreach}
						</ul>
						{if $access_mail}
							<p>{t}And the following users:{/t}</p>
						{/if}
					{else}
						{t}users:{/t}</p>
					{/if}
					<ul>
						{foreach $access_mail as $access}
							<li>{$access|escape}</li>
						{/foreach}
					</ul>
				{/if}
			</div>
		</div>
	</div>
	<div class="col-md-6">
		{if $settings_totp_enabled}
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">{t}Two-factor authentication{/t}</h3>
			</div>
			<div class="panel-body">
				{if $totp_success}
				<div class="alert alert-success">{t}Success! You have now enabled two-factor authentication for this account.{/t}</div>
				{/if}
				<p>{t}Helps protect your account, by requiring a one-time password generated by a mobile device to log in.{/t}</p>
				{if $totp_enabled or $totp_success}
				<p><a href="?page=user&totp_disable=true" class="btn btn-danger">{t}Disable{/t}</a></p>
				{else}
				<p><a href="?page=user&totp_enable=true" class="btn btn-primary">{t}Enable{/t}</a></p>
				{/if}
			</div>
		</div>
		{/if}
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">{t}Change password{/t}</h3>
			</div>
			<div class="panel-body">
				{if $password_changed}
					<div class="alert alert-success">{t}Password changed{/t}</div>
				{/if}
				{if $error}
					<div class="alert alert-danger">{$error|escape}</div>
				{/if}
				{if $password_changeable}
					<form class="form-horizontal" method="post" action="?page=user">
						<div class="form-group">
							<label class="col-sm-3 control-label" for="old_password">{t}Old Password{/t}</label>
							<div class="col-sm-9">
								<input type="password" class="form-control" name="old_password" id="old_password" placeholder="{t}Old password{/t}" autofocus>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label" for="password">{t}New Password{/t}</label>
							<div class="col-sm-9">
								<input type="password" class="form-control" name="password" id="password" placeholder="{t}New password{/t}">
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label" for="password2">&nbsp;</label>
							<div class="col-sm-9">
								<input type="password" class="form-control" name="password2" id="password2" placeholder="{t}Repeat new password{/t}">
							</div>
						</div>
						<div class="form-group">
							<div class="col-sm-offset-3 col-sm-10">
								<button type="submit" class="btn btn-primary">{t}Change{/t}</button>
							</div>
						</div>
					</form>
				{else}
					<p>
						{t}You are authenticated externally, so password changes are not done here.{/t}
					</p>
				{/if}
			</div>
		</div>
	</div>
	{/if}
</div>
{include file='footer.tpl'}
